server:
  servlet:
    context-path: "/api"
jwt:
  secret: ${JWT_SECRET}
swagger:
  enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpda_db
    username: nnpdaUser
    password: nnpdaPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect:org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
